Commited change in 587 schema file

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,41 +1,27 @@
 version: 0.2
 
 phases:
-  pre_build:
-    commands:
-      - echo Checking for rollback...
-      - bash scripts/rollback.sh
-
   build:
     commands:
+      - echo Cloning the repository...
+      - git clone https://github.com/MrinalBhoumick/AppSync-Structured.git /codebuild/repo
+      - cd /codebuild/repo
       - echo Creating AppSync API if it does not exist...
-      - bash scripts/create-api.sh || { echo "Build failed"; touch rollback.flag; exit 1; }
-
+      - bash scripts/create-api.sh
       - echo Updating schema...
-      - bash scripts/update-schema.sh || { echo "Build failed"; touch rollback.flag; exit 1; }
-
+      - bash scripts/update-schema.sh
       - echo Creating or updating the data source...
-      - bash scripts/create-update-data-source.sh || { echo "Build failed"; touch rollback.flag; exit 1; }
-
+      - bash scripts/create-update-data-source.sh
       - echo Updating request mapping templates...
-      - bash scripts/update-request-mapping-template.sh || { echo "Build failed"; touch rollback.flag; exit 1; }
-
+      - bash scripts/update-request-mapping-template.sh
       - echo Updating response mapping templates...
-      - bash scripts/update-response-mapping-template.sh || { echo "Build failed"; touch rollback.flag; exit 1; }
-
+      - bash scripts/update-response-mapping-template.sh
       - echo Updating Lambda authorizer...
-      - bash scripts/update-lambda-authorizer.sh || { echo "Build failed"; touch rollback.flag; exit 1; }
-
+      - bash scripts/update-lambda-authorizer.sh
   post_build:
     commands:
-      - echo "Build phase completed. Checking for rollback flag..."
-      - if [ -f rollback.flag ]; then
-        echo "Build failed. Performing rollback...";
-        bash scripts/rollback.sh;
-        exit 1;
-        else
-        echo "Build succeeded. No rollback needed.";
-        fi
+      - echo Build phase completed. Checking for rollback flag...
+      - if [ -f rollback.flag ]; then echo "Build failed. Performing rollback..."; bash scripts/rollback.sh; exit 1; else echo "Build succeeded. No rollback needed."; fi
 
 artifacts:
   files:
