Updated Mapping Template Configuration

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -47,10 +47,8 @@ jobs:
             bash scripts/update-schema.sh || { echo 'Schema update failed'; touch rollback.flag; exit 1; } && \
             echo Creating or updating the data source... && \
             bash scripts/create-update-data-source.sh || { echo 'Data source update failed'; touch rollback.flag; exit 1; } && \
-            echo Updating request mapping templates... && \
-            bash scripts/update-request-mapping-template.sh || { echo 'Request mapping update failed'; touch rollback.flag; exit 1; } && \
-            echo Updating response mapping templates... && \
-            bash scripts/update-response-mapping-template.sh || { echo 'Response mapping update failed'; touch rollback.flag; exit 1; } && \
+            echo Updating Mapping templates... && \
+            bash scripts/update-mapping-template.sh || { echo 'Mapping update failed'; touch rollback.flag; exit 1; } && \
             echo Updating Lambda authorizer... && \
             bash scripts/update-lambda-authorizer.sh || { echo 'Lambda authorizer update failed'; touch rollback.flag; exit 1; }"
 
